# Site settings
title: Emerald | A simple Jekyll blog
description: "A minimal blog template, build with Jekyll."
url: "https://fjsantim.github.io/emerald"
author:
  name: "Francisco J. Santiago"
  email: "fjsantim@gmail.com"
  url: "http://www.github.com/fjsantim"

# Build settings
baseurl: /emerald/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
#permalink: /:title

plugins:
  - jekyll-redirect-from
  - jekyll-paginate

paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
