# Site settings
title: Blog para cálculo III
description: "Este es un blog para ir añadiendo las tareas de Cálculo III"
url: "https://fjsantim.github.io/calculo-iii"
author:
  name: "Francisco J. Santiago"
  email: "fjsantim@gmail.com"
  url: "http://www.github.com/fjsantim"

# Build settings
baseurl: /calculo-iii/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
#permalink: /:title

plugins:
  - jekyll-redirect-from
  - jekyll-paginate

paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Disqus comments
comments: true      # used to enable disqus comments on site
dsq_shortname: https-fjsantim-github-io-calculo-iii # disqus shortname

# Options
custom_header: false
custom_nav_footer: false
reverse: false
